//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::FmvMaker.Core.Utilities.VideoBoolEvent))]
	public class PropertyProvider_FmvMaker_Core_Utilities_VideoBoolEvent : Unity.VisualScripting.SerializedPropertyProvider<FmvMaker.Core.Utilities.VideoBoolEvent>
	{
	}
}
